language: python
python:
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get install antlr4
# command to install dependencies
install:

  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge 
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pygraphblas pytest
  - conda activate test-environment

  - pip install -r requirements.txt
# command to run tests
script:
  - cd src/db-language && antlr4 -Dlanguage=Python3 -o ../ db_language.g4 && cd ../../
  - python -m pytest
